# render.yaml
services:
  - type: web
    name: your-laravel-app-name
    plan: free
    branch: your-branch-name # <- e.g., master
    dockerfilePath: Dockerfile # <- This line tells Render to use the Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
    # Add your other vars (APP_KEY, DB_*) in the Render Dashboard